// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVt8PA_0GgzxcpcM4vpvGQpTJF499PI3c',
    appId: '1:805281104403:web:edcbf29a8eb750cea975e6',
    messagingSenderId: '805281104403',
    projectId: 'sosuu-speed-2826a',
    authDomain: 'sosuu-speed-2826a.firebaseapp.com',
    databaseURL: 'https://sosuu-speed-2826a-default-rtdb.firebaseio.com',
    storageBucket: 'sosuu-speed-2826a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaVkM1P6FAHLY5ygsas4jVl3e1tBlBVXs',
    appId: '1:805281104403:android:884dd53f82c86d61a975e6',
    messagingSenderId: '805281104403',
    projectId: 'sosuu-speed-2826a',
    databaseURL: 'https://sosuu-speed-2826a-default-rtdb.firebaseio.com',
    storageBucket: 'sosuu-speed-2826a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGjj6AwqxB0XpRfSgV3Up9TIBWkXzpHc8',
    appId: '1:805281104403:ios:5f4f831ab1720115a975e6',
    messagingSenderId: '805281104403',
    projectId: 'sosuu-speed-2826a',
    databaseURL: 'https://sosuu-speed-2826a-default-rtdb.firebaseio.com',
    storageBucket: 'sosuu-speed-2826a.firebasestorage.app',
    iosBundleId: 'com.example.sosuuSpeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGjj6AwqxB0XpRfSgV3Up9TIBWkXzpHc8',
    appId: '1:805281104403:ios:5f4f831ab1720115a975e6',
    messagingSenderId: '805281104403',
    projectId: 'sosuu-speed-2826a',
    databaseURL: 'https://sosuu-speed-2826a-default-rtdb.firebaseio.com',
    storageBucket: 'sosuu-speed-2826a.firebasestorage.app',
    iosBundleId: 'com.example.sosuuSpeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVt8PA_0GgzxcpcM4vpvGQpTJF499PI3c',
    appId: '1:805281104403:web:06b969a433aae3d8a975e6',
    messagingSenderId: '805281104403',
    projectId: 'sosuu-speed-2826a',
    authDomain: 'sosuu-speed-2826a.firebaseapp.com',
    databaseURL: 'https://sosuu-speed-2826a-default-rtdb.firebaseio.com',
    storageBucket: 'sosuu-speed-2826a.firebasestorage.app',
  );
}
